### PR TITLE
Update rtest.py to the standardized version

### PR DESCRIPTION
**Pull request by cgmb**
This allows us to consolidate the two rtest xml files. See https://github.com/ROCmSoftwarePlatform/rocSOLVER/pull/319.

### CODE REVIEW

**Comment by cgmb** [comment]
[The gfx906 build is passing](http://mlsejenkinsvm.amd.com/blue/organizations/jenkins/Math%20Libraries%2FhipSOLVER/detail/PR-45/6/pipeline/252).

**Comment by cgmb** [comment]
@tfalders @eidenyoshida @lawruble13 @jzuniga-amd, could we try to get this in?

**Review by lawruble13 — APPROVED** [review]
LGTM

**Review by jzuniga-amd — APPROVED** [review]

**Comment by cgmb** [comment]
No prob. I wasn't expecting this to be important. It came as a bit of a surprise that it was necessary (and sufficient) to fix the build.

**Pull request merged**
