### PR TITLE
Added ormtr

### PR DESCRIPTION
**Pull request by tfalders**
Adds ormtr to hipSOLVER

### CODE REVIEW

**Review by jzuniga-amd — APPROVED** [review]
LGTM

**Review by cgmb — APPROVED** [review]
👍

**Comment by tfalders** [comment]
CI is failing because of a mismatch between rocBLAS and rocSOLVER, but it was passing before this mismatch occurred. Since the failures appear to not be related to this PR, I'm going to merge it now.

**Comment by cgmb** [comment]
hipSOLVER's CI wasn't getting updated rocSOLVER builds because develop was failing. That should be resolved soon, since a workaround has been merged (https://github.com/ROCmSoftwarePlatform/rocSOLVER/pull/262).

**Pull request merged**
