### PR TITLE
Added gels

### PR DESCRIPTION
**Pull request by tfalders**
Addresses SWDEV-309968.

### CODE REVIEW

**Review by jzuniga-amd — APPROVED** [review]
LGTM

**Comment by cgmb** [comment]
Hmm.... This is probably related to CI changes rather than hipSOLVER changes, but the CUDA build complains:
> CMake Error at /opt/rocm/hip/cmake/FindHIP.cmake:71 (message):
>  Specify HIP_ROOT_DIR

@eidenyoshida, have you seen this before?

**Comment by eidenyoshida** [comment]
I think the HIP_ROOT_DIR might be a mainline issue, our 4.5 job still passes.

mainline
http://math-ci.rocm.amd.com/blue/organizations/jenkins/cuda-mainline%2Ftestonly-precheckin-cuda%2FhipSOLVER/detail/PR-66/1/pipeline

4.5
http://math-ci.rocm.amd.com/blue/organizations/jenkins/compute-rocm-dkms-no-npi-hipclang%2Fprecheckin-cuda%2FhipSOLVER/detail/PR-66/7/pipeline

**Comment by cgmb** [comment]
This error is because [`FindHIP.cmake at line 58`](https://github.com/ROCm-Developer-Tools/HIP/blob/586165ebc281eb9461898a5b2abbc74595f5d97d/cmake/FindHIP.cmake#L56-L68) is looking for `bin/hipconfig` and can't figure out where it is. It searches `$ENV{ROCM_PATH}/hip"`, `ENV HIP_PATH`, `/opt/rocm/hip` and the `_IMPORT_PREFIX`.

**Review by cgmb — APPROVED** [review]
The test failures appear to be problem with our test containers. @eidenyoshida is looking into it.

**Pull request merged**
